"use client";

import { useMemo, useState } from "react";
import { Check, Download, Lock, Plus, Send, Trash2, Unlock } from "lucide-react";
import { download } from "@/lib/audio";

type Row = { id: string; name: string; role: string; pro: "ASCAP" | "BMI" | "SESAC" | "None"; ipi: string; email: string; pct: number; signed?: string };

const START: Row[] = [
  { id: "a", name: "Jay Rivers", role: "Artist / Writer", pro: "BMI", ipi: "00712345678", email: "jay@example.com", pct: 50 },
  { id: "b", name: "Nia Shift", role: "Producer", pro: "ASCAP", ipi: "00798765432", email: "nia@example.com", pct: 50 },
];

export default function SplitsPage() {
  const [song, setSong] = useState("Glass House (Remix)");
  const [rows, setRows] = useState<Row[]>(START);
  const [sent, setSent] = useState(false);
  const [signing, setSigning] = useState<string | null>(null);
  const [sig, setSig] = useState("");

  const total = useMemo(() => Math.round(rows.reduce((s, r) => s + (r.pct || 0), 0) * 100) / 100, [rows]);
  const valid = total === 100 && rows.every((r) => r.name.trim() && r.email.includes("@") && r.pct > 0);
  const signedCount = rows.filter((r) => r.signed).length;
  const unlocked = sent && signedCount === rows.length;

  const set = (id: string, patch: Partial<Row>) => setRows((rs) => rs.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  const even = () => {
    const base = Math.floor((100 / rows.length) * 100) / 100;
    setRows((rs) => rs.map((r, i) => ({ ...r, pct: i === 0 ? Math.round((100 - base * (rs.length - 1)) * 100) / 100 : base })));
  };

  const exportSheet = () => {
    const lines = [
      `SPLIT SHEET: ${song}`,
      `Generated by The Yard · ${new Date().toISOString().slice(0, 10)}`,
      "",
      ...rows.map((r) => `${r.name} | ${r.role} | ${r.pro} ${r.ipi} | ${r.pct}% | signed: ${r.signed ?? "pending"}`),
      "",
      `Total: ${total}%`,
    ];
    download(new Blob([lines.join("\n")], { type: "text/plain" }), `${song.replace(/\W+/g, "_")}_split_sheet.txt`);
  };

  let acc = 0;
  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Split Sheets</h1>
        <p className="text-xs text-white/50">Lock ownership before files move. Masters and stems stay gated until every collaborator signs.</p>
      </div>

      <div className="grid gap-5 xl:grid-cols-[1fr_300px]">
        <div className="space-y-4 rounded-3xl bg-white/[0.04] p-5">
          <label className="block text-xs text-white/55">Song title<input disabled={sent} value={song} onChange={(e) => setSong(e.target.value)} className="field mt-1 text-base" /></label>

          <div className="space-y-2">
            {rows.map((r) => (
              <div key={r.id} className="grid grid-cols-2 gap-2 rounded-2xl bg-black/25 p-3 2xl:grid-cols-[1.3fr_1fr_90px_1fr_80px_auto]">
                <input disabled={sent} value={r.name} onChange={(e) => set(r.id, { name: e.target.value })} placeholder="Legal name" className="field" aria-label="Legal name" />
                <input disabled={sent} value={r.role} onChange={(e) => set(r.id, { role: e.target.value })} placeholder="Role" className="field" aria-label="Role" />
                <select disabled={sent} value={r.pro} onChange={(e) => set(r.id, { pro: e.target.value as Row["pro"] })} className="field" aria-label="PRO">
                  {["ASCAP", "BMI", "SESAC", "None"].map((p) => <option key={p} className="bg-neutral-900">{p}</option>)}
                </select>
                <input disabled={sent} value={r.ipi} onChange={(e) => set(r.id, { ipi: e.target.value.replace(/\D/g, "").slice(0, 11) })} placeholder="IPI / PRO ID" className="field font-mono" aria-label="PRO ID" />
                <div className="relative">
                  <input disabled={sent} type="number" min={0} max={100} step={0.5} value={r.pct} onChange={(e) => set(r.id, { pct: +e.target.value })} className="field pr-6" aria-label="Percentage" />
                  <span className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-white/40">%</span>
                </div>
                <div className="flex items-center gap-2">
                  {sent ? (
                    r.signed ? (
                      <span className="flex items-center gap-1 text-xs text-[var(--color-lime)]"><Check size={13} /> {r.signed}</span>
                    ) : (
                      <button onClick={() => { setSigning(r.id); setSig(""); }} className="btn btn-light px-3 py-1 text-xs">Sign</button>
                    )
                  ) : (
                    <button disabled={rows.length <= 1} onClick={() => setRows((rs) => rs.filter((x) => x.id !== r.id))} aria-label="Remove" className="p-2 text-white/40 hover:text-white disabled:opacity-20"><Trash2 size={14} /></button>
                  )}
                </div>
                {!sent && <input value={r.email} onChange={(e) => set(r.id, { email: e.target.value })} placeholder="Email for e-signature" className="field col-span-2 2xl:col-span-6" aria-label="Email" />}
                {signing === r.id && (
                  <div className="col-span-2 flex flex-wrap items-center gap-2 2xl:col-span-6">
                    <input autoFocus value={sig} onChange={(e) => setSig(e.target.value)} placeholder={`Type "${r.name}" to sign`} className="field flex-1 font-[cursive] italic" />
                    <button
                      disabled={sig.trim().toLowerCase() !== r.name.trim().toLowerCase()}
                      onClick={() => {
                        set(r.id, { signed: new Date().toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) });
                        setSigning(null);
                      }}
                      className="btn btn-signal text-xs disabled:opacity-40"
                    >
                      Adopt & sign
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>

          {!sent && (
            <div className="flex flex-wrap items-center gap-2">
              <button onClick={() => setRows((rs) => [...rs, { id: Math.random().toString(36).slice(2), name: "", role: "Writer", pro: "None", ipi: "", email: "", pct: 0 }])} className="btn btn-ghost text-xs"><Plus size={13} /> Add collaborator</button>
              <button onClick={even} className="btn btn-ghost text-xs">Split evenly</button>
              <span className={`ml-auto font-mono text-sm ${total === 100 ? "text-[var(--color-lime)]" : "text-[var(--color-signal)]"}`}>{total}% / 100%</span>
              <button disabled={!valid} onClick={() => setSent(true)} className="btn btn-light text-xs disabled:opacity-40"><Send size={13} /> Send for signatures</button>
            </div>
          )}
          {!valid && !sent && <p className="text-[11px] text-white/45">Every collaborator needs a name, an email and a share, and shares must total exactly 100%.</p>}
        </div>

        <div className="space-y-4">
          <div className="rounded-3xl bg-white p-5 text-black">
            <svg viewBox="0 0 42 42" className="mx-auto h-40 w-40 -rotate-90">
              <circle cx="21" cy="21" r="15.9" fill="none" stroke="rgba(0,0,0,0.06)" strokeWidth="5" />
              {rows.map((r, i) => {
                const el = (
                  <circle key={r.id} cx="21" cy="21" r="15.9" fill="none" stroke={["#ff4d9d", "#b69cff", "#d7f542", "#111", "#7ce8ff", "#ffb35c"][i % 6]} strokeWidth="5" strokeDasharray={`${Math.max(0, r.pct - 0.6)} ${100 - Math.max(0, r.pct - 0.6)}`} strokeDashoffset={-acc} />
                );
                acc += r.pct;
                return el;
              })}
            </svg>
            <div className="mt-4 space-y-1.5 text-sm">
              {rows.map((r, i) => (
                <div key={r.id} className="flex items-center gap-2">
                  <i className="h-2.5 w-2.5 rounded-full" style={{ background: ["#ff4d9d", "#b69cff", "#d7f542", "#111", "#7ce8ff", "#ffb35c"][i % 6] }} />
                  <span className="flex-1 truncate">{r.name || "Unnamed"}</span>
                  <span className="font-mono text-xs">{r.pct}%</span>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-3xl bg-white/[0.04] p-5">
            <div className="flex items-center gap-2 text-sm">
              {unlocked ? <Unlock size={15} className="text-[var(--color-lime)]" /> : <Lock size={15} className="text-white/60" />}
              Download gate
            </div>
            <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10">
              <div className="h-full bg-[var(--color-lime)] transition-all duration-500" style={{ width: `${sent ? (signedCount / rows.length) * 100 : 0}%` }} />
            </div>
            <div className="mt-2 text-[11px] text-white/50">{sent ? `${signedCount} of ${rows.length} signed` : "Not sent yet"}</div>
            <div className="mt-4 space-y-2">
              {["Final Master.wav", "Stems.zip"].map((f) => (
                <button key={f} disabled={!unlocked} className="flex w-full items-center justify-between rounded-xl bg-black/25 px-3 py-2 text-sm disabled:opacity-40">
                  {f} {unlocked ? <Download size={14} /> : <Lock size={13} />}
                </button>
              ))}
              <button onClick={exportSheet} className="btn btn-ghost w-full text-xs">Export split sheet</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
